---
- name: check ssh port connection
  register: ssh_port_test
  delegate_to: 127.0.0.1
  wait_for:
        host: "{{inventory_hostname}}"
        port: 22
        state: started
        delay: 0
        timeout: 1
  ignore_errors: true

- name: check ssh authentication
  register: ssh_connection_test
  when: ssh_port_test is succeeded
  ping:
    crash: data
  ignore_unreachable: true

- name: set fresh_raspbian
  set_fact:
    fresh_raspbian: "{{ssh_port_test is succeeded and ssh_connection_test.unreachable is not defined}}"

